services:
  web:
    build: .
    container_name: checkin-app
    ports:
      - "5050:5050"
    volumes:
      - .:/app
      - ./instance:/app/instance  

    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "until pg_isready -h db -U $POSTGRES_USER; do sleep 2; done && python init_db.py && gunicorn -b 0.0.0.0:5050 server_pg:app"
    restart: always

  db:
    image: postgres:15
    container_name: checkin-db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
