version: "3.9"
services:
  web:
    build: .
    container_name: checkin-app
    ports:
      - "5050:5050"
    volumes:
      - .:/app
      - ./instance:/app/instance  # Mantiene le sessioni persistenti

    env_file:
      - .env
    environment:
      WEB_CONCURRENCY: "2"             
      GUNICORN_TIMEOUT: "120"           
      GUNICORN_EXTRA: "--worker-class gthread --threads 4 --keep-alive 10 --graceful-timeout 120 --max-requests 500 --max-requests-jitter 50"
      FILES_BASE_DIR: "/app/files_liste"   
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:


