name: Build and Push to GHCR

on:
  push:
    branches:
      - checkin-dev
  pull_request:

  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker image tag based on branch
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$BRANCH_NAME" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image to GHCR
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ env.IMAGE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ env.IMAGE_TAG }}
