name: Deploy to Test

on:
  push:
    branches:
      - test

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      APP_ENV: ${{ secrets.APP_ENV }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      OIDC_AUTH_URL: ${{ secrets.OIDC_AUTH_URL }}
      OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
      OIDC_REDIRECT_URI: ${{ secrets.OIDC_REDIRECT_URI }}
      OIDC_TOKEN_URL: ${{ secrets.OIDC_TOKEN_URL }}
      OIDC_USERINFO_URL: ${{ secrets.OIDC_USERINFO_URL }}

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Avvia Docker Compose (build + up)
        run: |
          docker-compose up --build -d